apiVersion: v1
kind: Pod
metadata:
  name: hello-node
spec:
  containers:
  - image: hello-node:v1
    name: hello-node
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
