apiVersion: v1
kind: Pod
metadata:
  name: hello-node
spec:
  containers:
  - image: hello-node:v1
    name: hello-node
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
