apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: docker.io/jocatalin/kubernetes-bootcamp:v1
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
    - name: cache-volume
      hostPath:
        # directory location on host
        path: /home/lxdeng/data
        # this field is optional
        type: DirectoryOrCreate
