kind: Service
apiVersion: v1
metadata:
  name: service-test
spec:
  selector:
    app: service_test_pod
  ports:
  - port: 80
    name: python-http # if not specified, it says <unset> when describe
    targetPort: http
  externalIPs:
  - 192.168.29.221   
